nameOverride: ""
fullnameOverride: ""

replicaCount: 1
application:
  port: 3000
  profile: dev

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  nodePort:

serviceAccount:
  create: false
  annotations: {}
  name: ""

image:
  repository: harbor.ha-ving.store/docker/711-front
  tag: "42c7dc34486d77890b3cdbcd536098559a3d0c6a"
  pullPolicy: IfNotPresent

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "ha-ving.store-issuer"
  hosts:
    - host: aptner.ha-ving.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: aptner-ingress
      hosts:
        - aptner.ha-ving.store

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

nodeSelector: {}

tolerations: []

affinity: {}